name: Tests

on:
  push:
  pull_request:

jobs:
  validation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Validate composer
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Check PHP syntax
        run: |
          find src -name "*.php" -print0 | xargs -0 -n1 php -l